export type Schedule = {
  timezone: string;
  kind: "interval" | "daily" | "weekly";
  start_at: string;
  interval_minutes: number;
  local_time: string;
  weekdays: number[];
};
export type AutomationTarget = {
  kind: "agent" | "workflow";
  id: string;
  version_id: string;
  payload_hash: string;
  activation_id: string | null;
};
export type AutomationPolicy = {
  overlap: "skip" | "queue";
  missed: "skip" | "catch_up";
  catch_up_limit: number;
  max_runs_per_day: number;
  max_tokens_per_task: number;
  max_attempts: number;
  backoff_seconds: number;
};
export type AutomationInput = {
  title: string;
  target: AutomationTarget;
  input: string;
  allow_remote_model: true;
  schedule: Schedule;
  policy: AutomationPolicy;
  expected_revision?: number | null;
};
export type SchedulerStatus = {
  authority: "core_single_owner";
  last_tick_at: string | null;
  error_code: string | null;
  local_device_off: string;
  availability_guarantee: false;
  native_jobs: false;
};
export type Automation = {
  id: string;
  organization_id: string;
  project_id: string;
  title: string;
  owner_actor_id: string;
  revision: number;
  configuration: AutomationInput;
  payload_hash: string;
  status: "paused" | "enabled";
  next_run_at: string;
  last_occurrence_id: string | null;
  created_at: string;
  updated_at: string;
  approval_verified?: boolean;
  preview?: { utc: string; local: string }[];
  scheduler?: SchedulerStatus;
};
export type Occurrence = {
  id: string;
  target_id: string;
  automation_id: string;
  occurrence_key: string;
  scheduled_at: string;
  definition_revision: number;
  payload_hash: string;
  status: string;
  attempts: number;
  retry_at: string | null;
  run_id: string | null;
  run_kind: "agent" | "workflow";
  error_code: string | null;
  created_at: string;
  completed_at: string | null;
};
export type AutomationEvent = {
  id: string;
  event: string;
  actor_id: string;
  created_at: string;
  occurrence_id: string | null;
  details: Record<string, unknown>;
};
export type Capability = {
  namespace: string;
  version: string;
  adapter: string;
  modes: ("local" | "hosted")[];
  risk: string;
  available: boolean;
  effective_permission: boolean;
  grants: string[];
  requirements: string[];
  missing_prerequisites: string[];
  disabled_reason: string | null;
};
export type CapabilityRegistry = {
  organization_id: string;
  project_id: string;
  mode: "local" | "hosted";
  checked_at: string;
  capabilities: Capability[];
  entitlement: "unknown";
  entitlement_reason: string;
  billing_category: "external_or_local";
  provider_hard_cost_cap: false;
  scheduler_authority: "core_single_owner";
  local_offline_execution: false;
};
