import {
  Beaker,
  Bot,
  FileText,
  FolderKanban,
  Fingerprint,
  LayoutDashboard,
  Radio,
  Settings,
  ShieldCheck,
  Terminal,
  Workflow,
} from "lucide-react";
export const navigation = [
  { path: "/", label: "Ringkasan", icon: LayoutDashboard, group: "WORKSPACE" },
  {
    path: "/projects",
    label: "Projects & Divisions",
    icon: FolderKanban,
    group: "WORKSPACE",
  },
  { path: "/factory", label: "Agent Factory", icon: Bot, group: "BUILD" },
  {
    path: "/workflows",
    label: "Workflow Builder",
    icon: Workflow,
    group: "BUILD",
  },
  {
    path: "/capabilities",
    label: "Capabilities",
    icon: ShieldCheck,
    group: "BUILD",
  },
  {
    path: "/operations",
    label: "Agent Operations",
    icon: Bot,
    group: "OPERATE",
  },
  {
    path: "/automations",
    label: "Automations",
    icon: Workflow,
    group: "OPERATE",
  },
  { path: "/runs", label: "Eksekusi", icon: Terminal, group: "OPERATE" },
  {
    path: "/outputs",
    label: "Outputs",
    icon: FileText,
    group: "OPERATE",
  },
  {
    path: "/brief",
    label: "Brief",
    icon: FileText,
    group: "INTELLIGENCE & RELIABILITY",
  },
  {
    path: "/bench",
    label: "Bench",
    icon: Beaker,
    group: "INTELLIGENCE & RELIABILITY",
  },
  {
    path: "/relay",
    label: "Relay",
    icon: Radio,
    group: "INTELLIGENCE & RELIABILITY",
  },
  {
    path: "/approvals",
    label: "Persetujuan",
    icon: ShieldCheck,
    group: "CONTROL",
  },
  {
    path: "/governance",
    label: "Tata Kelola",
    icon: Fingerprint,
    group: "CONTROL",
  },
  { path: "/settings", label: "Pengaturan", icon: Settings, group: "CONTROL" },
];
